name: Native image pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # windows instead of ubuntu so that the downloaded file will work on our computer
    steps:
      # check out our code to the runner
      - name: Checkout code
        uses: actions/checkout@v4
      # configure the runner to use GraalVM
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '17'
      # Create a step that uses the native-image command
      - name: Use native-image command
        run: mvn install -Pnative # mvn clean install -Pnative is better but without it's faster
      # upload the artifact created by the workflow that will make it available to download from Github
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: give artifact a name (this is the artifact id from the pom)
          path: target/hello-1.0-SNAPSHOT-runner.exe