name: Build pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check out our code to the runner
      - name: Checkout code
        uses: actions/checkout@v4
      # setup our JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      # split up compilation and testing
      - name: Build and test with Maven
        run: mvn clean install